feat: Add benchmarks, unit tests for audio analyser and refactoring gui

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -21,7 +21,7 @@ jobs:
 
     - name: Install dependencies
       run: |
-        brew install cmake ninja qt6 googletest
+        brew install cmake ninja qt6 googletest google-benchmark
 
     - name: Configure project
       run: |
@@ -37,3 +37,19 @@ jobs:
     - name: Run tests
       run: |
         ./build/tests
+
+    - name: Build benchmarks
+      run: |
+        cmake --build build --target benchmarks --parallel $(sysctl -n hw.ncpu)
+
+    - name: Run benchmarks and verify complexity
+      run: |        
+        OUTPUT=$(./build/benchmarks)
+        echo "$OUTPUT"
+        
+        if echo "$OUTPUT" | grep "RMS" | awk '{ if ($2 > 10) exit 1 }'; then
+          echo "Complexity RMS check passed."
+        else
+          echo "Complexity RMS check failed (exceeded 10% threeshold)!"
+          exit 1
+        fi
